### ISSUE TITLE
Dependencies errors when trying to install

### ISSUE THREAD

**Issue by newelement** [nickurt/laravel-akismet#10]
Greetings, I'm getting these composer errors when trying to install on Laravel 5.2

  Problem 1
    - Installation request for nickurt/laravel-akismet ^0.0.1 -> satisfiable by nickurt/laravel-akismet[0.0.1].
    - Conclusion: remove guzzlehttp/guzzle 6.1.1

    - Conclusion: don't install guzzlehttp/guzzle 6.1.1
    - nickurt/laravel-akismet 0.0.1 requires guzzlehttp/guzzle 5.* -> satisfiable by guzzlehttp/guzzle[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.1.0,
 5.2.0, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[5.0.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.1, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.2, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.0.3, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.1.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.2.0, 6.1.1].
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 6.1.1].
    - Installation request for guzzlehttp/guzzle == 6.1.1.0 -> satisfiable by guzzlehttp/guzzle[6.1.1].

**Comment by nickurt** [comment]
.@newelement, can you checkout branch dev-guzzle, I made it working for GuzzleHttp/Guzzle 5.3.0 & 6.2.0 (5.*/6.*), if it works for you I will merge it to master and will tag a new version.

**Comment by newelement** [comment]
Looks like that worked! Thanks

**Comment by nickurt** [comment]
I merged dev-guzzle to master and tagged a new version .. cc @newelement
