### ISSUE TITLE
Example of manually submitting spam/ham

### ISSUE THREAD

**Issue by BrookeDot** [nickurt/laravel-akismet#43]
Apologies if this is off topic but I am new to Laravel, I'm hoping to update the readme with an example of how to manually submit ham/spam.

It is unclear how you get the form data into ` \Akismet::reportSpam()` 

I am thinking it is something like:

```\Akismet::setCommentAuthor("John Doe")
    ->setCommentAuthorUrl("https://www.google.com")
    ->setCommentContent("It's me, John!")
    ->setCommentType('registration')
...

if( \Akismet::reportSpam() ) {
return true;
}
```

Any help would be appreciated.

**Comment by nickurt** [comment]
You are right, with the following functions (https://github.com/nickurt/laravel-akismet?tab=readme-ov-file#set-commentauthor-information)

```php
setUserIp
setUserAgent
setReferrer
setPermalink
setCommentType
setCommentAuthor
setCommentAuthorEmail
setCommentAuthorUrl
setCommentContent
setBlogUrl
setIsTest
```
Or you can use the mass-assign function 

```php
fill
```

Before calling the reportSpam (https://github.com/nickurt/laravel-akismet?tab=readme-ov-file#submit-spam-missed-spam)

```php
reportSpam
```

**Comment by BrookeDot** [comment]
Thanks, I'll give that a go. Marking a closed for now! 

I've done this before with the [fuspam function ](https://www.whatsmyip.org/lib/fuspam-akismet-php/) which does work, but it's nice to have a more modern and native way for Laravel :D
