### ISSUE TITLE
Allow URL to be Null

### ISSUE THREAD

**Issue by BrookeDot** [nickurt/laravel-akismet#44]
Currently there is validation that is preventing the URL field from being invalid. However, this returns an MalformedURLException error when null is passed. 

Ideally, null would be supported as the author URL is optional according to [the Akismet docs](https://akismet.com/developers/detailed-docs/comment-check/). I can open a PR adding `&& $commentAuthorUrl !== NULL` to the check, but let me know if you have a better idea.

The error happens here:
https://github.com/nickurt/laravel-akismet/blob/master/src/Akismet.php#L308-L312

Cheers,

**Comment by nickurt** [comment]
Can you make a PR with a test to verify this, then I can merge it pretty fast

**Comment by nickurt** [comment]
Hi @BrookeDot and @stephdau, thanks for the info, just released v2, which support null/empty string for ```setCommentAuthorUrl```
