### ISSUE TITLE
Fatal Exception 'Empty "blog" value'

### ISSUE THREAD

**Issue by BrookeDot** [nickurt/laravel-akismet#46]
When submitting to Akismet v2 returns `Empty "blog" value` from the Akismet API. I opened #45 with more details.

I'm not sure how long this was an issue as the x-debug exception was added with v2. 

Possibly related to #6 but that was so long ago who knows ;)

**Comment by nickurt** [comment]
Thanks [BrookeDot](https://github.com/BrookeDot), just released v2.0.1
