### ISSUE TITLE
validateKey always returns  Empty "api_key" value.

### ISSUE THREAD

**Issue by bartjuh4** [nickurt/laravel-akismet#47]
Since we've updated to ^2.0 validateKey() always returns nickurt\Akismet\Exception\AkismetException  Empty "api_key" value.

I've tried some config clear en re-publish config actions but the same issue remains.

Are there more people having this issue?

**Comment by nickurt** [comment]
Hi, what if you try this by `validateKey`

```php
$response = Http::post

->

$response = Http::asForm()->post
```

**Comment by bartjuh4** [comment]
Yep, that worked

```Psy Shell v0.12.4 (PHP 8.3.13 — cli) by Justin Hileman
> \Akismet::validateKey()
= true
```

**Comment by nickurt** [comment]
Ok, tagged 2.0.2 with fix
