### ISSUE TITLE
Null values issue

### ISSUE THREAD

**Issue by garygreen** [nickurt/laravel-akismet#6]
I've just been debugging an issue for a while before realizing that it's submitting `blog` as `null` and erroring with: 

> "Missing required field: blog."

All of the values that are being submitted as `null` should be empty strings otherwise akismet won't process the request.

**Comment by garygreen** [comment]
ping @nickurt this is pretty much breaking the whole package

**Comment by garygreen** [comment]
Bump. Any news @nickurt ?

**Comment by nickurt** [comment]
I can't repro it here, did what you told about it but I got an error then. Did you have a snipped/example what I can try?

**Comment by nickurt** [comment]
What version of guzzle did you used @malinthe ? Can you show me your composer.json require/-dev, then I can look into it.

**Comment by malinthe** [comment]
@nickurt It was Guzzle 6.2

My composer.json file:

```json
"require": {
	"laravel/framework": "5.1.*",
	"facebook/php-sdk-v4": "^4.0",
	"guzzlehttp/guzzle": "^6.0",
	"barryvdh/laravel-ide-helper": "^2.0",
	"barryvdh/laravel-debugbar": "^2.0",
	"guzzlehttp/psr7": "^1.1",
	"intervention/image": "^2.3",
	"greggilbert/recaptcha": "dev-master",
	"sunra/php-simple-html-dom-parser": "v1.5.0",
	"nickurt/laravel-akismet": "dev-master"
},
"require-dev": {
	"phpunit/phpunit": "~4.0",
	"phpspec/phpspec": "~2.1",
	"mockery/mockery": "~0.9.2"
}
```

**Comment by nickurt** [comment]
I tested it and it works here fine (nginx/php7) ...

    Route::get('/', function () {
        $akismet = \Akismet::validateKey();
    
        dd($akismet);
    });

Did you get an error or something else?

**Comment by malinthe** [comment]
I've mentioned the error I receive below. The same code works locally on Apache/PHP5 without any issues.

```php
FatalThrowableError in Akismet.php line 427:
Wrong parameters for Exception([string $message [, long $code [, Throwable $previous = NULL]]])

in Akismet.php line 427
at Exception->__construct(array('Empty "blog" value')) in Akismet.php line 427
at Akismet->getResponseData('https://xxxxxxxx.rest.akismet.com/1.1/comment-check') in Akismet.php line 375
```
